### PR TITLE
Override container runtime for commands

### LINKED ISSUE #179: [BUG] cannot use Docker if podman machine is not running
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Konveyor version

latest

### Priority

Major

### Current Behavior

Trying to run kantra with Docker: `RUNNER_IMG=kantra:docker PODMAN_BIN=/usr/local/bin/docker go run main.go analyze`
Was getting error:

```
Error: Cannot connect to Podman. Please verify your connection to the Linux system using podman system connection list, or try podman machine init and podman machine start to manage a new Linux VM
```

Once I started a podman machine, the command worked. Although I was not using a podman image/bin. 

### Expected Behavior

Should be able to run kantra using docker without a podman machine running.

### How Reproducible

Always (Default)

### Steps To Reproduce

_No response_

### Environment

```markdown
- OS: Mac M1
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by eemcmullan**
Closes #179

### CODE REVIEW

File: cmd/analyze.go [hunk 1]
```diff
@@ -309,6 +309,7 @@ func (a *analyzeCommand) ListLabels(ctx context.Context) error {
 			container.WithEnv(runMode, runModeContainer),
 			container.WithVolumes(volumes),
 			container.WithEntrypointBin(fmt.Sprintf("/usr/local/bin/%s", Settings.RootCommandName)),
+			container.WithContainerRuntimeBin(os.Getenv("PODMAN_BIN")),
```
Comment (pranavgaikwad) [inline cmd/analyze.go:312]: can we rename containerRuntime to containerTool everywhere as it's not accurate? also, should we be using the PODMAN_BIN from the settings as we have some logic to auto-detect things too?

**Review by pranavgaikwad — CHANGES_REQUESTED** [review]

**Comment by pranavgaikwad** [comment]
@eemcmullan I also think that this should not cherry-picked because this is introduced in my most recent fix which itself isn't cherry-picked (it is for 0.4)

File: cmd/analyze.go (hunk 1 above)
Comment (shawn-hurley) [reply cmd/analyze.go:312]: I am plus one on the re-name myself

**Review by pranavgaikwad — APPROVED** [review]

**Review by shawn-hurley — APPROVED** [review]
