### PR TITLE
:fix :(docs): changed env PODMAN_BIN to CONTAINER_TOOL

### LINKED ISSUE #168: Rename `PODMAN_BIN` to `CONTAINER_TOOL` with backward compatibility
This came up in https://github.com/konveyor/kantra/pull/165: now that kantra will automatically fall back to `docker` if `podman` isn't present, `PODMAN_BIN` doesn't make quite as much sense. Renaming it to `CONTAINER_TOOL` would help clarify what the override is actually overriding.

Continuing to accept `PODMAN_BIN` and forwarding it to `CONTAINER_TOOL` means this doesn't need to be a breaking change. (I don't mind if this is a breaking change myself, though, just an idea.)

A name other than `CONTAINER_TOOL` is fine with me, it does seem like an easy pick though. I also took a look in k8s and see that name being used: https://github.com/search?q=org%3Akubernetes-sigs+CONTAINER_TOOL&type=code

### PR DESCRIPTION
**Pull request by soham4abc**
This PR changes the environment variable `PODMAN_BIN` to `CONTAINER_TOOL`

as kantra falls back to docker if podman is not present, this variable name makes much more sense.

@dagood Please do have a look and provide any necessary feedback for the same.

Closes #168

### CODE REVIEW

File: cmd/settings.go [hunk 1]
```diff
@@ -24,7 +24,7 @@ const (
 
 type Config struct {
 	RootCommandName      string `env:"CMD_NAME" default:"kantra"`
-	PodmanBinary         string `env:"PODMAN_BIN" default:"/usr/bin/podman"`
+	PodmanBinary         string `env:"CONTAINER_TOOL" default:"/usr/bin/podman"`
```
Comment (dagood) [inline cmd/settings.go:27]: My only question here would be whether kantra should keep supporting `PODMAN_BIN` as an alias of `CONTAINER_TOOL` for compatibility reasons. (Realized my paragraph about this was unclear in https://github.com/konveyor/kantra/issues/168, so I've edited it to reword.)

I'm not sure either way. (And to be clear, I'm not a maintainer of the repo.)

Comment (soham4abc) [reply cmd/settings.go:27]: @eemcmullan your views on this?

Comment (eemcmullan) [reply cmd/settings.go:27]: I think it's fine to move ahead with `CONTAINER_TOOL` without supporting `PODMAN_BIN`. We will then probably want to update instances of  the `podmanBinary` field to something like `containerToolBinary`, but I don't think that was covered in the issue, and it's not a user-facing var, so I am okay with these changes. Thanks for the contribution!

**Review by eemcmullan — APPROVED** [review]

File: cmd/settings.go (hunk 1 above)
Comment (soham4abc) [reply cmd/settings.go:27]: Welcome @eemcmullan do let me know if further changes are required before merging!!

**Comment by eemcmullan** [comment]
@soham4abc apologies for the confusion. After discussing with @shawn-hurley we think it's best to support `PODMAN_BIN` for a while longer. Can we first check for this var? If `CONTAINER_TOOL` is also set, we will want to use that instead.

**Comment by soham4abc** [comment]
> @soham4abc apologies for the confusion. After discussing with @shawn-hurley we think it's best to support `PODMAN_BIN` for a while longer. Can we first check for this var? If `CONTAINER_TOOL` is also set, we will want to use that instead.

Sure... Do you want me to revert the changes to ```PODMAN_BIN?

**Comment by eemcmullan** [comment]
@soham4abc We still want to move forward with `CONTAINER_TOOL`. But for the sake of compatibility, we should probably check for `PODMAN_BIN` and `CONTAINER_TOOL` together. If both are set, use `CONTAINER_TOOL`. If only one or the other, use that.

**Comment by soham4abc** [comment]
> @soham4abc We still want to move forward with `CONTAINER_TOOL`. But for the sake of compatibility, we should probably check for `PODMAN_BIN` and `CONTAINER_TOOL` together. If both are set, use `CONTAINER_TOOL`. If only one or the other, use that.

hey @eemcmullan I have made the changes can you please have a look and test on your end!

**Comment by soham4abc** [comment]
@eemcmullan any guidance on solving this particular error?

File: cmd/settings.go [hunk 2]
```diff
@@ -24,6 +24,7 @@ const (
 
 type Config struct {
 	RootCommandName      string `env:"CMD_NAME" default:"kantra"`
+	ContainerBinary      string `env:"CONTAINER_TOOL" default:"/usr/bin/podman"`
```
Comment (eemcmullan) [inline cmd/settings.go]: CI is failing because this field will need to also be updated where it is being accessed in the rest of the project. This will be where the different commands run. Please let me know if you have any questions on it.

Comment (soham4abc) [reply cmd/settings.go]: As of the latest changes I removed the default path.

**Comment by soham4abc** [comment]
@eemcmullan can you please have a look and run the CI tests?

File: cmd/settings.go [hunk 3]
```diff
@@ -53,8 +54,8 @@ func (c *Config) Load() error {
 }
 
 func (c *Config) loadDefaultPodmanBin() error {
-	// Respect existing PODMAN_BIN setting.
-	if os.Getenv("PODMAN_BIN") != "" {
+	// Respect existing CONTAINER_TOOL setting.
+	if os.Getenv("CONTAINER_TOOL") != "" || os.Getenv("PODMAN_BIN") != "" {
```
[the remark this answers is not in the document]
Comment (soham4abc) [reply cmd/settings.go]: Thanks a lot for the review @eemcmullan. I have pushed the recent changes!

**Review by eemcmullan — APPROVED** [review]

**Comment by soham4abc** [comment]
@shawn-hurley can you please have a look at the changes and provide your reviews?

File: docs/developer.md [hunk 4]
```diff
@@ -1,14 +1,14 @@
 ### Running kantra
 
-Two environment variables control the container runtime and the kantra image: `PODMAN_BIN` and `RUNNER_IMG`:
-- `PODMAN_BIN`: path to your container runtime (podman or docker)
+Two environment variables control the container runtime and the kantra image: `CONTAINER_TOOL` and `RUNNER_IMG`:
+- `CONTAINER_TOOL`: path to your container runtime (podman or docker)
```
Comment (shawn-hurley) [inline docs/developer.md:4]: nit: container tool not container runtime. 

Container Runtimes are actually different things https://kubernetes.io/docs/setup/production-environment/container-runtimes/ and in this case we don't work with most container runtimes we work with a container tool which is IMO something different. 

We can fix this on a follow up though

**Review by shawn-hurley — APPROVED** [review]
One minor nit

File: docs/developer.md (hunk 4 above)
Comment (soham4abc) [reply docs/developer.md:4]: Thanks for the review @shawn-hurley! 


@eemcmullan do let me know if this PR needs any more changes
