### PR TITLE
Use Default Rules for Profile if Default Source or Target

### LINKED ISSUE #693: [BUG] Analysis by profile leaves an empty report
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Konveyor version

0.9 alpha 5

### Priority

Blocker

### Current Behavior

Analysis using downloaded profile works, but report is empty

### Expected Behavior

Report should contain relevant issues/insights/dependencies

### How Reproducible

Always (Default)

### Steps To Reproduce

1. Pull profile from the hub
2. Run analysis with this profile

### Environment

```markdown
- OS: Fedora 43
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by eemcmullan**
Fixes #693 

## Summary by CodeRabbit

* **Bug Fixes**
  * Fixed profile rule loading behavior: default rulesets are now conditionally disabled based on explicit flag usage, providing more accurate control over rule configuration.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

File: pkg/profile/profile.go [hunk 1]
```diff
@@ -112,7 +112,11 @@ func SetSettingsFromProfile(path string, cmd *cobra.Command, settings *ProfileSe
 		}
 		if len(profileRules) > 0 {
 			settings.Rules = append(settings.Rules, profileRules...)
-			settings.EnableDefaultRulesets = false
+			targetFlag := cmd.Flags().Lookup("target")
+			sourceFlag := cmd.Flags().Lookup("source")
+			if (targetFlag == nil || !targetFlag.Changed) && (sourceFlag == nil || !sourceFlag.Changed) {
+				settings.EnableDefaultRulesets = false
```
Comment (jmle) [inline pkg/profile/profile.go]: So if the target/source is not set we don't use the default rulesets?

**Review by jmle — APPROVED** [review]
