### PR TITLE
:bug: Fix no-cleanup option, disable analysis logs to stdout

### LINKED ISSUE #55: Log level should be passed down to analyzer cli

### LINKED ISSUE #92: [BUG] Reduce logging verbosity
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Konveyor version

latest from Oct 19 2023

### Priority

Minor

### Current Behavior

Running kantra produces ~3500 lines of output

### Expected Behavior

Less verbose output, would think the default output is much less

### How Reproducible

Always (Default)

### Steps To Reproduce

I'm running kantra on the below source application:
 - https://github.com/ivargrimstad/jakartaee-duke/tree/start-tutorial

`./kantra analyze -i /Users/jmatthews/git/SAMPLES/jakartaee-duke -t “jakarta-ee9+” -o /Users/jmatthews/RedHat/MTA/out`

Here is an example of the output produced:
https://gist.github.com/jwmatthews/5ef3fec3e3d5574921bb0256f106c8b4

### Environment

```markdown
- OS: Mac M1
```

### Anything else?

Maybe related to https://github.com/konveyor/kantra/issues/55

### PR DESCRIPTION
**Pull request by pranavgaikwad**
Fixes #92 
Fixes #55

* Disables analysis logs to stdout 
* Passes down log level to analyzer command
* Adds log files for all commands and prints logs there
* Replaces deprecated ioutil.WriteFile with os.WriteFile

### CODE REVIEW

File: cmd/analyze.go [hunk 1]
```diff
@@ -561,31 +569,35 @@ func (a *analyzeCommand) RunAnalysis(ctx context.Context, xmlOutputDir string) e
 
 	a.log.Info("running source code analysis", "log", analysisLogFilePath,
 		"input", a.input, "output", a.output, "args", strings.Join(args, " "), "volumes", volumes)
+	a.log.Info("generating analysis log in file", "file", analysisLogFilePath)
```
Comment (eemcmullan) [inline cmd/analyze.go:572]: +1

**Review by eemcmullan — APPROVED** [review]

**Review by djzager — APPROVED** [review]
