### PR TITLE
use err for lookpath

### LINKED ISSUE #113: [BUG] Don't Eat Error on looking up podman exec path error
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Konveyor version

latest

### Priority

Undefined (Default)

### Current Behavior

_No response_

### Expected Behavior

_No response_

### How Reproducible

Always (Default)

### Steps To Reproduce

_No response_

### Environment

```markdown
- OS:
```

### Anything else?

cmd/settings.go line 31 is the offending code

### PR DESCRIPTION
**Pull request by eemcmullan**
Closes #113

### CODE REVIEW

File: cmd/settings.go [hunk 1]
```diff
@@ -28,7 +28,10 @@ type Config struct {
 func (c *Config) Load() error {
 	envValue := os.Getenv("PODMAN_BIN")
 	if envValue == "" {
-		podmanPath, _ := exec.LookPath("podman")
+		podmanPath, err := exec.LookPath("podman")
+		if err != nil {
+			return err
```
Comment (pranavgaikwad) [inline cmd/settings.go:33]: I think the idea was to only error when you see a `errors.Is(err, ErrDot)`

**Review by pranavgaikwad — CHANGES_REQUESTED** [review]

File: cmd/settings.go (hunk 1 above)
Comment (eemcmullan) [reply cmd/settings.go:33]: @pranavgaikwad  Looks like `exec.ErrDot` requires go 1.19: https://pkg.go.dev/os/exec 
We may need to update the Dockerfile too?

Comment (pranavgaikwad) [reply cmd/settings.go:33]: yes, analyzer-lsp is using 19 as well

**Review by pranavgaikwad — APPROVED** [review]
