### PR TITLE
Fix profile validation & using default rules with profiles

### LINKED ISSUE #702: [CCM] Error: must specify rules if default rulesets are not enabled
This validation errors if default rulesets are disabled and `--rules` are not passed in. If a profile with rules is included in the application, this should not happen.

### LINKED ISSUE #703: [CCM] --profile-dir with rules does not set any rules

### PR DESCRIPTION
**Pull request by eemcmullan**
Fixes #702 
Fixes #703 

## Summary by CodeRabbit

* **New Features**
  * Analyze command loads and applies analysis profiles from configured or default locations; validation now respects profile-driven settings and logs profile usage or absence.
  * Profile inspection detects presence of rule files and default labels to influence default-ruleset behavior.

* **Refactor**
  * Streamlined, path-driven profile resolution and application flow with clearer conditional logging.

* **Bug Fixes**
  * More descriptive errors for profile resolution and loading failures.

* **Tests**
  * Extensive unit tests for profile loading, rule detection, validation, and default-ruleset scenarios.

### CODE REVIEW

File: pkg/profile/profile.go [hunk 1]
```diff
@@ -102,8 +103,23 @@ func SetSettingsFromProfile(path string, cmd *cobra.Command, settings *ProfileSe
...
+		// use default rulesets if default sources/targets are used
+	} else {
+		targetSet := cmd.Flags().Lookup("target") != nil && cmd.Flags().Lookup("target").Changed
+		sourceSet := cmd.Flags().Lookup("source") != nil && cmd.Flags().Lookup("source").Changed
+		hasDefaultLabels := profileHasDefaultKonveyorLabels(profile)
+		settings.EnableDefaultRulesets = targetSet || sourceSet || hasDefaultLabels
+	}
+
+	// add rules from profile directory if not set via command line
 	if !cmd.Flags().Lookup("rules").Changed {
```
Comment (jmle) [inline pkg/profile/profile.go]: I guess this is part of the spec, but wouldn't we want to use both the profile rules _and_ the rules specified in `--rules`? Just wondering

**Review by jmle — CHANGES_REQUESTED** [review]
I left some questions - we also need tests

**Review by shawn-hurley — COMMENTED** [review]
Just making sure that options I pass via CLI override the profile configuration right?

File: pkg/profile/profile.go (hunk 1 above)
Comment (shawn-hurley) [reply pkg/profile/profile.go]: I think anything passed via the CLI should be used. Anything else I think is surprising behavior.

**Comment by eemcmullan** [comment]
@shawn-hurley correct that's the current behavior

**Review by shawn-hurley — APPROVED** [review]

**Review by jmle — APPROVED** [review]
